version: '3' #docker-compose.yml
networks:
  integration:
services:
  jenkins: #JENKINS
    image: jenkins/jenkins:2.138.3
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    # entrypoint: ./jenkins/entrypoint.sh
    networks:
    - integration
    volumes:
      - ./jenkins/home:/var/jenkins_home:rw #Remember that, the tmp directory is designed to be wiped on system reboot.
      - ./jenkins/install/install_jenkins_plugins.sh:/install_jenkins_plugins.sh
      - ./jenkins/install/plugins.txt:/plugins.txt
      - ./jenkins/entrypoint.sh:/entrypoint.sh
    restart: always
  otus_jenkins:
    container_name: otus_jenkins
    image: nginx:1.15.5
    command:
      - 'nginx'
      - '-g'
      - 'daemon off;'
    restart: always
    privileged: true
    user: root
    depends_on:
      - jenkins
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - integration
    ports:
      - 80:80
      - 443:443
    links:
      - jenkins
