version: '3' #docker-compose.yml
networks:
  integration:
services:
  jenkins: #JENKINS
    image: jenkins/jenkins:2.138.3
    privileged: true
    user: root
    ports:
      - 8282:8080
      - 50000:50000
    container_name: jenkins
    networks:
    - integration
    volumes:
      - ./jenkins/home:/var/jenkins_home:rw #Remember that, the tmp directory is designed to be wiped on system reboot.
      - ./jenkins/install/install_jenkins_plugins.sh:/install_jenkins_plugins.sh
      - ./jenkins/install/plugins.txt:/plugins.txt

