version: '3' #docker-compose.yml
networks:
  integration:
services:
  sonarqube: #SONAR
    image: sonarqube:6.4
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    # networks:
    # - integration
    # volumes:
      # - ./sonarqube/persistence/conf:/opt/sonarqube/conf
      # - ./sonarqube/persistence/data:/opt/sonarqube/data
      # - ./sonarqube/persistence/logs:/opt/sonarqube/logs
      # - ./sonarqube/persistence/extensions:/opt/sonarqube/extensions
 
    # volumes:
    # - mediawiki_db:/var/lib/mysql
# volumes:
  # mediawiki_images:
  # mediawiki_db:
